name: nxv
channels:
  - conda-forge
  - mantid/label/nightly
dependencies:
  - python>=3.11
  - numpy
  - scipy
  - matplotlib
  - pycifrw
  - h5py
  - pyvista>=0.45.2
  - pyvistaqt
  - vtk
  - pytest
  - mantid
  - scikit-learn
  - scikit-image
  - astropy
  - dill
  - psutil
  - multiprocess
  - black
  - pip:
    - pyqtdarktheme
    -pyoncat
