# GitHub Actions workflow for building and testing NeuXtalViz-tools
# This workflow sets up Python, installs dependencies, and runs tests using pytest.

name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy scipy matplotlib pyvista pyvistaqt qtpy scikit-image
          # If you have a requirements.txt, uncomment the next line:
          # pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/
