# GitHub Actions workflow for building and testing NeuXtalViz-tools
# This workflow sets up Python, installs dependencies, and runs tests using pytest.

name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: nxv

      - name: Run tests
        run: pytest tests/
