# GitHub Actions workflow for building and testing NeuXtalViz-tools
# This workflow sets up Python, installs dependencies, and runs tests using pytest.

name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniforge
        uses: conda-incubator/setup-miniforge@v2
        with:
          miniforge-variant: Miniforge
          python-version: ${{ matrix.python-version }}

      - name: Create environment from environment.yml
        run: |
          conda env create -f environment.yml

      - name: Activate environment and run tests
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate nxv
          pytest tests/
