name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.11
        activate-environment: base

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base

    - name: Run tests with pytest
      run: |
        pytest
