name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniforge
      uses: conda-incubator/setup-miniforge@v2
      with:
        python-version: 3.11
        miniforge-variant: Miniforge
        use-mamba: true   # Optional: for faster environment solving

    - name: Install dependencies
      run: |
        mamba env update --file environment.yml --name base

    - name: Run tests with pytest
      run: |
        mamba install pytest
        pytest
