name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda with nxv environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.11
        environment-file: environment.yml
        activate-environment: nxv

    - name: Install package in editable mode
      shell: bash -l {0}  # activate conda environment
      run: |
        python -m pip install -e .
  
    - name: Run tests with pytest
      shell: bash -l {0}  # ensures conda environment is active
      run: |
        pytest
