name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.5.1

    - name: Install dependencies
      run: |
        pixi install

    - name: Run tests with pytest
      run: |
        pixi run pytest
